### ISSUE TITLE
切换到另一个ai的时候，就会自动刷新

### ISSUE THREAD

**Issue by joeaki1983** [lencx/Noi#11]
这个功能没必要，能不能去掉，还有就是当ChatGPT登录了一个谷歌账户，另一个perplexity也会登录同一个谷歌账户，且无法切换。

**Comment by lencx** [comment]
这不是我开发的功能啊，你在浏览器测一样的。它会检测已登陆过的 google 账号，自动登录，我认为这是 perplexity 自己的问题。
