### ISSUE TITLE
Windows系统中界面UI有些不符合预期

### ISSUE THREAD

**Issue by lainbo** [lencx/Noi#12]
复现过程
1. 点击最大化按钮

**疑似出现的问题**
左下角的图标被遮挡
![image](https://github.com/lencx/Noi/assets/46062895/8e858159-fef1-4997-a899-cc5cd323d291)

**Comment by lencx** [comment]
这个问题已知，下个版本修复。

**Comment by lencx** [comment]
已修复，请下载 v0.3.0
