### ISSUE TITLE
How does one update the app?

### ISSUE THREAD

**Issue by mathmul** [lencx/Noi#125]
### Goal

Updating to a newer version.

### Setup

Noi 0.3.0
Windows 11 Pro

### What I tried and failed with

- Searching through all the menu to find "Update"
- Searching through Settings
- Checking out "About"
- Restarting Noi, to see if it checks for updates on startup
- `Ctrl+F` searching for `"update"` on [README](https://github.com/lencx/Noi)
- Searching for `"update"` through open and closed issues.

### A working workaround

Download new version from [releases](https://github.com/lencx/Noi/releases).

### Note

Close the issue A.S.A.P., if this is the intended behaviour. I just thought to open an issue for others in the future who might go through the same thought process.

**Comment by lencx** [comment]
Currently, updates can only be downloaded manually; it does not support automatic updates.

**Comment by mathmul** [comment]
Thank you. Marked as "Not planned" for the time being.
