### ISSUE TITLE
项目如何编译呢

### ISSUE THREAD

**Issue by jamosnet** [lencx/Noi#127]
并没有找到编译的方法

**Comment by lencx** [comment]
项目核心并不开源，不支持二次编译

**Comment by jamosnet** [comment]
原来这样啊，产品很好的，我想重新编译增加一个功能，因为默认代理功能不支持授权的代理，想软件默认启动一个外部程序，功能是把一个授权的sock5转非授权的socks5，
https://github.com/KaranGauswami/socks-to-http-proxy/releases/download/v0.4.0/sthp-windows.exe
sthp -p 1080 --listen-ip 127.0.0.1  -s  1.2.3.4:1080 -u usename -P password

软件默认启用代理，并且代理是 socks5://127.0.0.1:1080

这样推荐给朋友就可以开箱即用了。
