### ISSUE TITLE
ARM64 Mac build is damaged

### ISSUE THREAD

**Issue by drewbitt** [lencx/Noi#128]
<img width="258" alt="image" src="https://github.com/lencx/Noi/assets/26885897/d564731b-de8c-4023-8d3f-9bfebb90726f">

M2 Pro on MacOS Sonoma 14.4.1
0.4.0

**Comment by drewbitt** [comment]
I will not run `xattr` to trust this; please sign the application in the near future. Thank you.

**Comment by djbritt** [comment]
This fixed it for me - xattr -cr /Applications/Noi.app

https://github.com/lencx/Noi/issues/18#issuecomment-1915407681
