### ISSUE TITLE
Windows系统下Noi Ask输入异常

### ISSUE THREAD

**Issue by lainbo** [lencx/Noi#13]
Noi Ask中, 使用搜狗输入法、百度输入法, 都只能输入一次, 后续文字无法输入

https://github.com/lencx/Noi/assets/46062895/d919c859-4281-4163-8e51-052e92d82c6a

**Comment by lencx** [comment]
系统输入法呢？我目前没有验证各种输入法，因为要实现输入同步，这里进行了一些比较复杂的程序处理。

**Comment by lainbo** [comment]
微软拼音输入法也有此现象发生

https://github.com/lencx/Noi/assets/46062895/b9034aed-8876-4cef-b146-76da2f7d05af

**Comment by lencx** [comment]
我排查一下，如果找到问题了，下个版本解决。临时可以将整段消息复制粘贴进下面的输入框，也是可以同步到所有 AI 中的。

**Comment by lencx** [comment]
已修复，请下载 v0.3.0
