### ISSUE TITLE
proxy设置

### ISSUE THREAD

**Issue by haso2007** [lencx/Noi#14]
希望加入，必竞要使用各种代理

**Comment by lencx** [comment]
可以试试这种方式 https://electronjs.org/docs/latest/api/command-line-switches

可以通过快捷键设置：![image](https://github.com/lencx/Noi/assets/16164244/82e468b8-b594-4140-a191-41969bf0349a)

**Comment by haso2007** [comment]
优秀

**Comment by chrislouis0106** [comment]
怎么用呢，兄弟
