### ISSUE TITLE
书签增加导出和文件导入的方式

### ISSUE THREAD

**Issue by lzhcccccch** [lencx/Noi#142]
我想要在多个不同的设备中实现书签同步，我不知道现在在应用中应该怎么实现。
如果已经有方式可以实现，请大佬回复一下；
如果没有的话，我有两个想法大佬参考一下：
1.书签增加导出的功能，这样可以将自定义的书签导出，进行备份，方便多设备使用。
2.书签增加读取文件的形式，这样就可以通过网盘（比如 ICloud）在本地的文件夹实现多端自动同步。

**Comment by lencx** [comment]
虽然没有做导出功能，但是可以自己去找这个目录（`<NoiRoot>`）：
- Windows: `C:\Users\username\AppData\Roaming\Noi`
- macOS: ` ~/Library/Application\ Support/Noi`

目录中的 `<NoiRoot>/noi_cache/cache.mode.json` 文件是当前侧栏的数据（它是缓存数据，合并了同步数据和用户自定义数据。它可以带走，但不建议直接编辑），编辑后可能会被其他操作覆盖。在 `<NoiRoot>/noi_configs` 目录中的文件（原始数据）可以进行编辑：
- `<NoiRoot>/noi_configs/noi.mode.json`：通过点击侧栏左下角按钮同步过来的数据
- `<NoiRoot>/noi_configs/user.mode.json`：用户自己添加的侧栏数据。

在这里建议带走 `<NoiRoot>/noi_configs/noi.mode.json` 和 `<NoiRoot>/noi_configs/user.mode.json` 两个文件。

**Comment by lzhcccccch** [comment]
学会了，感谢~
