### ISSUE TITLE
copilot登录不上去

### ISSUE THREAD

**Issue by lelelaileabc** [lencx/Noi#15]
![微信截图_20240126165237](https://github.com/lencx/Noi/assets/8361688/dad17ad7-1623-402a-8b85-b421237a245f)

一直弹登录窗口，win11

**Comment by lencx** [comment]
我还没遇到过类似情况，请检查一下节点，尝试开启全局代理模式试试。

**Comment by lelelaileabc** [comment]
开了全局没好，刚电脑更新重启了下，突然可以打开了。真是扯淡的逻辑

**Comment by lencx** [comment]
这和 Noi 逻辑没啥关系啊，登录不上是因为 copilot 有自己的登录检测机制...
