### ISSUE TITLE
是否支持多窗口

### ISSUE THREAD

**Issue by PierXuY** [lencx/Noi#17]
请问目前版本支持多窗口吗？ 可以在多个工具之间自由切换。
如果能有拖拽分屏功能就更舒服了。

**Comment by langZhuYao** [comment]
实测还不支持，甚至切换工具再切回去就需要重新刷新。。效率就有点慢了，可能是我使用方法不正确？期待开发者的回复

**Comment by lencx** [comment]
Noi 的使用场景区别于常规浏览器，它主要是解决单个网页的专注度，然后在此基础上进行功能拓展。

**Comment by Jackiexiao** [comment]
如果不支持多窗口，建议不要在 README.md 中放上多窗口的图片，会产生误导 @lencx
