### ISSUE TITLE
“Noi” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by Arhan13** [lencx/Noi#180]
### Description

On downloading the macOS arm64 version from [noi.nofwl.com](https://noi.nofwl.com/), I seem to be getting this error:
`“Noi” is damaged and can’t be opened. You should move it to the Bin.`

### macOS Version

Version 14.4.1 (23E224)

### Device Details

M1 MacBook Pro

### Screenshot
<img width="264" alt="Screenshot 2024-05-31 at 1 22 15 AM" src="https://github.com/lencx/Noi/assets/60483503/d2080bd5-c996-4fe2-91df-746b884cfc74">

**Comment by djbritt** [comment]
@Arhan13 What did you do? I am on an m1 mac having the same issue.
