### ISSUE TITLE
安装新版后，prompt提示没了

### ISSUE THREAD

**Issue by JYKiki** [lencx/Noi#207]
安装新版后，prompt提示没了
<img width="498" alt="image" src="https://github.com/user-attachments/assets/361ea36b-35fb-4d0a-b33b-3a7432c620b8">

扩展也更新了
<img width="555" alt="image" src="https://github.com/user-attachments/assets/9c6947db-6057-42d1-bbba-74772a0601d1">

也存在用户prompt 以前是可以的
<img width="554" alt="image" src="https://github.com/user-attachments/assets/f27c6de8-50d6-468e-971c-e4d13090d680">

**Comment by lencx** [comment]
点击截图 1 右侧第二个小图标切换一下，你可能进入了输入记录模式。

**Comment by JYKiki** [comment]
！！！！靠谱！
