### ISSUE TITLE
窗口无法缩小

### ISSUE THREAD

**Issue by wadezyj** [lencx/Noi#211]
win 11笔记本电脑，有外接屏幕，推测是将窗口拉到外接屏幕，然后断开了HDMI线，后续又接上HDMI线。
目前是窗口充满了整个屏幕，并且占据了任务栏，无法拉小，也无法缩小。
![image](https://github.com/user-attachments/assets/d994aa3b-a467-4a29-b872-52d8cbdb93e7)

**Comment by ZLangChuan** [comment]
我也需要了这个问题 应用没办法 自定义窗口尺寸
