### ISSUE TITLE
Feature Request: Make shortcuts configurable

### ISSUE THREAD

**Issue by diomonogatari** [lencx/Noi#22]
This might be overcomplicating BUT...
![image](https://github.com/lencx/Noi/assets/17832206/d5644f6b-4e80-448b-9867-dd75558bd119)

I'm loving it so much that to me, the only thing "missing" is being able to setup my own shortcut preferences for improved navigation and what-not.
The ultimate "goal" would be to be able to configure Noi as if it was a big IDE.

Please let me know if you need further detail!

Kind regards,
Dio

**Comment by lencx** [comment]
❤️ Thank you for your suggestion.

Implementing universal shortcuts is a substantial undertaking, and currently, my primary focus is on the development of essential features. The basic shortcuts in Noi will align with standard browser shortcuts. Over time, I'll introduce more customizable shortcuts specific to Noi, enabling users to tailor them to their preferences. This process of enhancing and fine-tuning the details will take considerable time.

**Comment by lencx** [comment]
Version 0.3.0 already supports two types of shortcut settings. I wonder if it can meet some of your needs?

<img width="801" alt="shortcut" src="https://github.com/lencx/Noi/assets/16164244/df438350-61e0-4c59-965d-189dcfd9ca2d">

**Comment by diomonogatari** [comment]
Hey there 👋

I've recently updated and immediately found these new additions.
Looks good and the future seems promising!

Thank you for your time developing this tool for anyone to use!
