### ISSUE TITLE
Noi ask prompts not entering data for ChatGPT 

### ISSUE THREAD

**Issue by Jaykurb** [lencx/Noi#227]
I raised the issue in #206 where chatGPT does not appear in Noi ask and used your [workaround] by adding to the Noi cache(https://github.com/lencx/Noi/issues/206#issuecomment-2251134342). 

This allows ChatGPT to appear in Noi ask but no text is entered into ChatGPT when using noi ask prompts (it does on all the other platforms). 

![image](https://github.com/user-attachments/assets/6df6a0c5-2192-40bd-b903-4df58604e826)

**Comment by nachocheeseburger** [comment]
this worked for me.. https://github.com/lencx/Noi/issues/204

**Comment by Jaykurb** [comment]
Thank you, I missed that.
