### ISSUE TITLE
新修复的noi ask中按enter以后对于chatgpt不是换行而是直接发送消息

### ISSUE THREAD

**Issue by Dx-wmc** [lencx/Noi#234]
我使用了新的noi ask插件，虽然可以修复chatgpt输入的问题，但是一按enter就会直接发送消息，而不是换行

**Comment by wcool1** [comment]
并且Noi ask里仍然GPT仍然无法读取面板中的提示词
![Uploading image.png…]()

**Comment by lencx** [comment]
已更新代码，请更新 noi-ask 至 v0.1.11。
