### ISSUE TITLE
Gemini在多窗口的时候，noi ask不能键入prompt

### ISSUE THREAD

**Issue by ZhenhongDu** [lencx/Noi#242]
多窗口的时候，noi ask不能键入prompt
![image](https://github.com/user-attachments/assets/6b47ccea-c1e2-483d-8717-81db10fc56df)
单个窗口是正常的

noi ask扩展已经更新到最新
![image](https://github.com/user-attachments/assets/1cb6ba18-2017-432f-9907-a0eacfd214c8)

**Comment by ZhenhongDu** [comment]
但是chatgpt+poe在多窗口是可行的。

**Comment by ZhenhongDu** [comment]
类似于#130，在单个窗口有效，多窗口并排使用时无效；https://github.com/lencx/Noi/issues/130#issue-2230146367

**Comment by lencx** [comment]
我这边尝试了一下，gemini 是可以的呀，你确定它单独使用可以，多个使用无效吗？

**Comment by ZhenhongDu** [comment]
是的。不止gemini, 还有一些我自己加的网站

这个是我同时用的
https://github.com/user-attachments/assets/1f8a76dc-ccd6-4ea1-bfbc-e213cecd3830

这个是我只用了gemini
https://github.com/user-attachments/assets/82d2e1fd-9ec4-4108-b624-902ede5c1147

@lencx 麻烦大佬排查一下

**Comment by ZhenhongDu** [comment]
这个是我自己添加的网站，到noi_ask_custom里面的
https://github.com/user-attachments/assets/6d956002-2179-4afb-901d-afae15b06aad

多个面板同时用的时候也是不可以

这个是main.js
```
// NextChat
class NextChatAsk extends NoiAskCustom {
  static name = 'NextChat';
  static url = 'https://app.nextchat.dev';

  static sync(message) {
    const inputElement = document.querySelector('textarea[class*="chat_chat-input"]');
    if (inputElement) {
      this.simulateUserInput(inputElement, message);
    }
  }

  static autoFocus() {
    const inputElement = document.querySelector('textarea[class*="chat_chat-input"]');
    if (inputElement) {
      inputElement.focus();
    }
  }
  
  static submit() {
    const btn = document.querySelector('button[class*="chat_chat-input-send"]');
    if (btn) {
      this.autoClick(btn);
    }
  }
}

```
下面是manifest.json

```
{
  "manifest_version": 3,
  "name": "@noi/ask-custom",
  "version": "0.1.0",
  "homepage": "https://github.com/lencx/Noi/tree/main/extensions/noi-ask-custom",
  "description": "The best assistant for batch asking and quick typing of prompts.",
  "content_scripts": [
    {
      "matches": [
        "https://app.nextchat.dev/*",
        "https://demo.fuclaude.com/*",
        "https://kimi.moonshot.cn/*"
      ],
      "js": ["main.js"],
      "run_at": "document_end",
      "world": "MAIN"
    }
  ]
}

```

Gemini的代码我没有改过，是github上插件的最新版本

**Comment by ZhenhongDu** [comment]
我发现他在Noi ask模式下就是失效的（只有一个窗口的时候也不行），但是非noi ask模式就是正常的
![image](https://github.com/user-attachments/assets/d469b2c6-9bfd-4fb9-9ffa-9c96aa94a35e)
非Noi ask模式
![image](https://github.com/user-attachments/assets/778e328e-a081-4943-bf6b-1727d3f97b47)

**Comment by tangzeyu7** [comment]
我这边gemini和千问都是可以的,@noi/ask版本为0.1.12,@noi/ask-custom未修改过
![image](https://github.com/user-attachments/assets/13b0e6e0-9f25-46ce-90a1-516dc02510d5)

**Comment by tangzeyu7** [comment]
@ZhenhongDu 你个gemini的url和我这边相比多了层`/app`

**Comment by ZhenhongDu** [comment]
> @ZhenhongDu 你个gemini的url和我这边相比多了层`/app`
设置的时候后面改成删掉app的了
![image](https://github.com/user-attachments/assets/bbf37fbc-1e54-49c7-bd80-b5527654e928)

**Comment by ZhenhongDu** [comment]
@tangzeyu7 hello, 你是windows系统吗

**Comment by tangzeyu7** [comment]
> @tangzeyu7 hello, 你是windows系统吗

对的

**Comment by ZhenhongDu** [comment]
> > @tangzeyu7 hello, 你是windows系统吗
> 
> 对的

哦哦，奇怪了。我也是windows, 我卸载重装一下试下

**Comment by lencx** [comment]
> > @ZhenhongDu 你个gemini的url和我这边相比多了层`/app`
> > 设置的时候后面改成删掉app的了
> > ![image](https://private-user-images.githubusercontent.com/61380549/376093506-bbf37fbc-1e54-49c7-bd80-b5527654e928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjA2OTcsIm5iZiI6MTcyODk2MDM5NywicGF0aCI6Ii82MTM4MDU0OS8zNzYwOTM1MDYtYmJmMzdmYmMtMWU1NC00OWM3LWJkODAtYjU1Mjc2NTRlOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOWJjNTYzZmM3N2EwMTU1NThlNjA4YmYyMTBmNjFlY2FiYTMzMzVkMmNiOGM2MzMwZTA4MmI5ZGNjMThmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aHL24_KJ9suxyTuwuth_6OXYpdySqg7a0oCe9SbPg_g)

你可以尝试将 url 后的斜杠删掉，我不确定它会不会影响匹配（侧栏的 url 要和 noi-ask/main.js 方法中的 `static url = ""` 保持一致）。改成 `https://gemini.google.com`

**Comment by ZhenhongDu** [comment]
> > > @ZhenhongDu 你个gemini的url和我这边相比多了层`/app`
> > > 设置的时候后面改成删掉app的了
> > > ![image](https://private-user-images.githubusercontent.com/61380549/376093506-bbf37fbc-1e54-49c7-bd80-b5527654e928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjA2OTcsIm5iZiI6MTcyODk2MDM5NywicGF0aCI6Ii82MTM4MDU0OS8zNzYwOTM1MDYtYmJmMzdmYmMtMWU1NC00OWM3LWJkODAtYjU1Mjc2NTRlOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOWJjNTYzZmM3N2EwMTU1NThlNjA4YmYyMTBmNjFlY2FiYTMzMzVkMmNiOGM2MzMwZTA4MmI5ZGNjMThmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aHL24_KJ9suxyTuwuth_6OXYpdySqg7a0oCe9SbPg_g)
> 
> 你可以尝试将 url 后的斜杠删掉，我不确定它会不会影响匹配（侧栏的 url 要和 noi-ask/main.js 方法中的 `static url = ""` 保持一致）。改成 `https://gemini.google.com`

@lencx 还真是，去掉斜杆就可以了。谢谢大家！困扰很久的问题
