### ISSUE TITLE
Possible to multiple login same service?

### ISSUE THREAD

**Issue by stl3** [lencx/Noi#246]
~~I was wondering if it's possible to login same service using work account and personal account, and if already possibly what do I need to do (edit json somewhere?). Eg chatgpt, etc. is it a simple as just making new entry or a little more complex due to cookies?~~
```
Cookie Data Isolation: Supports the use of multiple accounts on the same website, catering to diverse user requirements.
```

**Comment by frijheid** [comment]
The new entry I made using the unique name cache is still leaking to the main chatgpt. Is there a mistake I commit?

**Comment by PP9995** [comment]
no work
