### ISSUE TITLE
自行添加了一个连接后，底部的提示词按钮如何打开？

### ISSUE THREAD

**Issue by loogg** [lencx/Noi#25]
我添加了一个国内的 ai 对话网，但是打开后，底部没有 Prompt 按钮，有哪里可以配置么？
![image](https://github.com/lencx/Noi/assets/28485255/67766a66-b738-46cd-99a0-c14e0af0a618)

**Comment by lencx** [comment]
添加任意网站后，还需要配套的插件来支持才行，你可以把网址发一下。

**Comment by loogg** [comment]
> 添加任意网站后，还需要配套的插件来支持才行，你可以把网址发一下。

https://ai.ashuiai.com/home

这个，我主要是想也能通过底部的 Prompt 按钮直接选择我自己添加的提示词填入到对话框，而不需要去设置界面复制后再拷贝到对话框里

![image](https://github.com/lencx/Noi/assets/28485255/e4177e14-6c1a-49d1-b9fe-17184dfb2637)

**Comment by lencx** [comment]
不好意思，非主流 AI 我没有账号，无法进行调试（建议参考：https://github.com/lencx/Noi/tree/main/extensions/noi-ask/main.js 中的实现，自己实现脚本）。

**Comment by loogg** [comment]
> 不好意思，非主流 AI 我没有账号，无法进行调试（建议参考：https://github.com/lencx/Noi/tree/main/extensions/noi-ask/main.js 中的实现，自己实现脚本）。

大佬我试了下，发现有几个问题

1. 在 Noi Ask 界面下不能打开开发者工具看调试，我也不知道我写的有没有生效，可能由于 2. 中的造成没生效？
2. Noi 重新打开会造成 NoiAsk 插件添加的所有都被重置（这个我看最新的提交中增加了 Custom 的文件，后续应该可以在这个文件中添加）
3. 这个只是 NoiAsk 的插件，对用户自己添加的链接调用，单个链接页面下的 Prompt 后续能否开放配置呢
4. NoiAsk 下把页面关闭后，必须得去 `cache.mode.json` 中配置才行，这个后续会可视化配置么

**Comment by lencx** [comment]
关于插件生效的问题你要等下一个版本的更新，目前是半成品，它每次打开应用都会重写目录。关于这块内容，我后面会写教程来说明用户如何接入自己使用的 AI 网站。

**Comment by loogg** [comment]
> 关于插件生效的问题你要等下一个版本的更新，目前是半成品，它每次打开应用都会重写目录。关于这块内容，我后面会写教程来说明用户如何接入自己使用的 AI 网站。

好的，非常期待，我也在向我的朋友推荐这个工具，非常好用

**Comment by lencx** [comment]
这里写了两篇文章介绍 Noi，可以看一下，第二篇着重介绍了插件相关的内容：
- https://mp.weixin.qq.com/s/dAN7LOw7mH609HdAyEvXfg
- https://mp.weixin.qq.com/s/M6gO6MdK5obCvs2LIBZA3w

**Comment by loogg** [comment]
谢谢，已基于 custom 插件实现啦



 

发件人: ***@***.*** ***@***.***> 代表 lencx
发送时间: 2024年2月11日 22:19
收件人: lencx/Noi ***@***.***>
抄送: 马龙伟 ***@***.***>; Author ***@***.***>
主题: Re: [lencx/Noi] 自行添加了一个连接后，底部的提示词按钮如何打开？ (Issue #25)

 

这里写了两篇文章介绍 Noi，可以看一下，第二篇着重介绍了插件相关的内容：

*	https://mp.weixin.qq.com/s/dAN7LOw7mH609HdAyEvXfg
*	https://mp.weixin.qq.com/s/M6gO6MdK5obCvs2LIBZA3w
