### ISSUE TITLE
[Bug] Chatgpt在分屏且窗口小于一定宽度的时候无法使用enter发送消息

### ISSUE THREAD

**Issue by EaglePPP** [lencx/Noi#252]
Chatgpt在分屏且窗口小于一定宽度的时候无法使用enter发送消息
别的ai没有测试

**Comment by lencx** [comment]
chatgpt 在小窗口下，会自动切换到手机模式。这是官网的默认行为，和 Noi 无关。如果你想继续使用 enter 来发送消息，需要使用 Noi 提供的输入框。
