### ISSUE TITLE
win11使用v0.4.0版本，无法打开chatgpt

### ISSUE THREAD

**Issue by morongs** [lencx/Noi#263]
电脑：win11
版本：v0.4.0
代理工具：v2ray

chrome浏览器能正常打开youtube或chatgpt，但Noi不行

问题情况：
网络能正常打开百度
![image](https://github.com/user-attachments/assets/8bf653ab-c33a-46a8-96b0-9e858a764855)

但是无法进入youtube或者chatgpt这些站点
![image](https://github.com/user-attachments/assets/ca2232e9-57e1-4755-80d8-d32cded3ddea)
![image](https://github.com/user-attachments/assets/072e4203-f705-490c-a725-7418d9d7326b)

点击同步更新也提示网络错误
![image](https://github.com/user-attachments/assets/417c856b-4b29-46eb-9c8d-42503b3d80e1)

尝试卸载重装还有移除和添加Noi里面的代理规则都一样打不开~

**Comment by Xnjikol** [comment]
感觉像是没走系统代理，用TUN模式试下呢？

**Comment by lencx** [comment]
你大概率是通过规则在访问，可以在 Noi 设置中配置一下代理规则（可以避免开全局代理）。

<img width="800" alt="Screenshot 2024-11-14 at 20 10 21" src="https://github.com/user-attachments/assets/bf5b17e3-ab12-4543-b937-fb932d7c16c4">

**Comment by morongs** [comment]
> 感觉像是没走系统代理，用TUN模式试下呢？

开启TUN后可以了

**Comment by lxsq** [comment]
> > 感觉像是没走系统代理，用TUN模式试下呢？
> 
> 开启TUN后可以了

TUN模式相当于全局了，这个代理还是没有生效
