### ISSUE TITLE
代理设置未生效

### ISSUE THREAD

**Issue by lxsq** [lencx/Noi#264]
开启代理后设置未生效，代理软件中未见入站。
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/15d93471-121f-431e-b358-2cfeaf444ba9">
<img width="395" alt="image" src="https://github.com/user-attachments/assets/46e01b92-1af8-4a20-b503-e1d8bf03638b">
直接使用Chrome浏览器和代理可以正常打开
<img width="695" alt="image" src="https://github.com/user-attachments/assets/cb0a2c8c-daed-4790-beea-f79d9adc7a32">

**Comment by lxsq** [comment]
**软件版本**
[Noi-win32-x64-0.4.0-setup.exe](https://github.com/lencx/Noi/releases/download/v0.4.0/Noi-win32-x64-0.4.0-setup.exe)
**系统版本**
```
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎7/‎30
操作系统版本	22631.4460
体验	Windows Feature Experience Pack 1000.22700.1047.0
```

**Comment by lencx** [comment]
Noi 中的代理只是规则设置，我看你的截图好像没输入内容呀。

**Comment by lxsq** [comment]
> Noi 中的代理只是规则设置，我看你的截图好像没输入内容呀。

抱歉打扰了，是我Proxifier规则设置的有问题，和项目无关。
