### ISSUE TITLE
claude镜像网站字体配置

### ISSUE THREAD

**Issue by Dx-wmc** [lencx/Noi#298]
我最近发现 Claude 的不同版本（官方网页版、NOI 版和镜像站）在字体显示上存在差异。特别注意到 NOI 版本的字体效果相当不错，我猜测可能是经过了专门的优化。请问有什么方法可以将镜像站的字体配置调整为与 NOI 版本一致呢？

左图是NOI，右图是镜像。我个人更喜欢NOI的claude字体配置。
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/d50a4439-f96d-41d5-98f3-ca1b6721f02e">

**Comment by lencx** [comment]
这倒没有做过什么额外处理，会不会是因为类 chrome 系列的浏览器都这样渲染？

**Comment by Dx-wmc** [comment]
这个就不知道了，chrome 和safari 的字体都是右图这样的
