### ISSUE TITLE
Feature Request: Add Built-in Proxy Setting Feature

### ISSUE THREAD

**Issue by Winger-Wang** [lencx/Noi#3]
**Feature Request**

Please consider adding a built-in proxy setting feature to simplify proxy configuration for users who need to connect to services via proxy servers. This feature will improve user convenience and accessibility.

**Implementation Suggestions:**

- Add a "Proxy Settings" section in the browser's settings menu.
- Allow users to enter proxy server details (e.g., IP address, port, authentication credentials) within the application.
- Ensure compatibility with various proxy protocols (e.g., HTTP, SOCKS).

**Comment by Ghastly2001** [comment]
I have coded a function in a seperate file in extentions path: extention/noi-proxy-settings/main.js 

Please have a look in my forked repo.

**Comment by Winger-Wang** [comment]
I have tried manually setting up this extension in my working dir. However, I can't see it popping up in the settings page in the app. Tried reboot but no help. Is there anything I am missing here?

**Comment by lencx** [comment]
Please download version v0.3.0 and find the proxy settings in the settings.

<img width="798" alt="proxy" src="https://github.com/lencx/Noi/assets/16164244/bb540f29-7bf6-47de-bf64-8fe535144440">

**Comment by momcilo330** [comment]
Not sure how to assign proxy url into the Proxy Rules input.
http://username:pass@ip:port
