### ISSUE TITLE
将来有考虑代理的问题吗？

### ISSUE THREAD

**Issue by zsui2354** [lencx/Noi#30]
将来有考虑添加代理规则吗？实现不同的网站的代理分流，比如我平时就习惯访问chatGPT用机场的节点，访问一些X、Youtube、Github之类的用VPS节点，我正想如何在Noi中将他们代理分流

**Comment by lencx** [comment]
针对 URL 进行分流可能比较麻烦，我需要思考一下。

**Comment by lencx** [comment]
请下载 v0.3.0，打开 settings，配置 proxy，尝试是否满足需要。

**Comment by zsui2354** [comment]
满足需要了，谢谢
