### ISSUE TITLE
Is there the source code of the app? And how to build it?

### ISSUE THREAD

**Issue by xaionaro** [lencx/Noi#311]
In this repository I find only scripts to build the website, but I don't find how to build the desktop app. Is the source code of the app even published? If so, then how can I build it locally?

**Comment by lencx** [comment]
Sorry, the core code of Noi is not open source.

**Comment by xaionaro** [comment]
My view is that generally software distributed via GitHub is presumed to be opensource. So if this is a closed source product it would be nice to have some explicit notification about that. Either adding a LICENSE file or adding a remark in the README.md.
