### ISSUE TITLE
win11

### ISSUE THREAD

**Issue by KAIKI12** [lencx/Noi#37]
win11自动全屏导致底部无法同时打开别的软件

**Comment by ColdCat-ship-it** [comment]
Hi Kaiki12,

我在使用期间没发现相关问题，有没有截图可以分享一下？
![image](https://github.com/lencx/Noi/assets/62545397/4fb5b5c7-21f9-4290-93c0-686faf57df37)

**Comment by lencx** [comment]
如果没有别的疑问，这个问题就先关闭了。
