### ISSUE TITLE
Feature Request: Search bar for every window or globe windows

### ISSUE THREAD

**Issue by JamesJian-tech** [lencx/Noi#38]
Hi Lencx,

Search function is useful for users to quickly find out the keyword.

1. Search bar
2. High the keywords 

Thanks.

**Comment by lencx** [comment]
Currently developing a web content search feature for the next release.

https://github.com/lencx/Noi/assets/16164244/49002baa-de19-40af-8f8c-5adaecd83658

**Comment by mathmul** [comment]
Note to other Brave users. If video won't play, try Chrome. Worked for me.

**Comment by lencx** [comment]
Please download v0.4.0.
