### ISSUE TITLE
不同模型TAB切换， ChatGpt 切换至 Bard后再切换回 ChatGpt ， 页面需要重载

### ISSUE THREAD

**Issue by dongbingliu** [lencx/Noi#44]
不同模型TAB切换， ChatGpt 切换至 Bard后再切换回 ChatGpt ， 页面需要重载

是否可以像浏览器一样， 不同的标签页切换后， 资源不回收♻️，继续保持原有的界面信息 ？

**Comment by forhonourlx** [comment]
+1 我也想知道图里的多窗口模型如何在windows下操作？
![image](https://github.com/lencx/Noi/assets/16576219/9d5948a6-6353-4019-aa33-bc682e796a00)
@lencx 求助大佬！

**Comment by lencx** [comment]
相关 issues: https://github.com/lencx/Noi/issues/17

暂不做支持的原因，我有解释过 https://x.com/lencx_/status/1751135177303343349?s=20

**Comment by dongbingliu** [comment]
> 相关 issues: #17
> 
> 暂不做支持的原因，我有解释过 https://x.com/lencx_/status/1751135177303343349

用户体验不怎么好，但也能接受

**Comment by forhonourlx** [comment]
> > 相关 issues: #17
> > 暂不做支持的原因，我有解释过 https://x.com/lencx_/status/1751135177303343349
> 
> 用户体验不怎么好，但也能接受

附议+1。恳请大佬再考虑考虑保存渲染视图，比方说能不能做成一个配置选项，给用户配置的自由？
我们普通用户存在非常多的误操作/大脑短路/变卦的场景：比如开着noi-ask多窗口，想加个模型，结果单击直接刷新转向了，很多对话没有可靠的断点继续，于是嘴里爆句粗口，心里尤为不爽，反而打断专注，非常影响体验。再次恳请大佬三思，感谢！ @lencx

**Comment by lencx** [comment]
这个其实我已经在构思了，为了可能会实现一个 Pin 的功能，来满足多开 View（类似于浏览器 Tab）。但这个实现不会很快，需要再等等了。

**Comment by dongbingliu** [comment]
很开心大佬能把此功能添加到 TBD 选项中去。 👏

**Comment by lencx** [comment]
请下载 v0.4.0 版本，此功能已实现。
