### ISSUE TITLE
Prompt 能否实现任何应用中的输入框通过快捷键使用

### ISSUE THREAD

**Issue by loogg** [lencx/Noi#46]
类似于 DeepL 我可以通过快捷键调出它的功能，后续能否实现在例如在 WPS AI 的输入框中我通过快捷键调用出 Prompt 提示框进行选择已激活的提示词

![image](https://github.com/lencx/Noi/assets/28485255/700a86da-5a9e-4a82-96aa-c680fe419b6c)

![image](https://github.com/lencx/Noi/assets/28485255/d6c39eaa-2165-433b-aeba-fb9d6d6e5d44)

**Comment by lencx** [comment]
没太明白，你可以简单画个流程图吗？

你说的快捷键唤起  Prompt 提示框（这个应该是指 Noi 的 Prompt），目标输入框呢（Noi 之外的地方）？

**Comment by loogg** [comment]
1. 打开 Noi
2. 打开某个应用，例如 WPS
3. 使用键盘快捷键例如 Ctrl+Win+C 调出 Prompt 提示界面
4. 在 Prompt 界面输入 / 命令选择提示词
5. 点击确定按钮把提示词填入 WPS AI 的输入框中

![image](https://github.com/lencx/Noi/assets/28485255/c2780056-5984-42e2-aa39-735f692bddac)

**Comment by lencx** [comment]
要把 Prompt 填入另一个 App 涉及到通信问题，我最多可以让它复制到剪贴板，让用户自己来粘贴到其他 App。

**Comment by loogg** [comment]
> 要把 Prompt 填入另一个 App 涉及到通信问题（脱离 Noi 范围，我无法操作），最多可以让它复制到剪贴板，让用户自己来粘贴到其他 App。

可以，确定按钮可以修改成这个复制到剪贴板，这样的话 Noi 就很通用了，这不是把什么那个某某某卖课 提示词的那个打爆掉

**Comment by lencx** [comment]
我会重新开发一个界面，来简化操作流程，比如通过全局快捷键唤醒 Prompts 面板，上下键选择，回车直接复制。

从长远来看，后期可以衍生出很多有趣的东西，比如记事本之类的。

**Comment by loogg** [comment]
> 我会重新开发一个界面，来简化操作流程，比如通过全局快捷键唤醒 Prompts 面板，上下键选择，回车直接复制。
> 
> 从长远来看，后期可以衍生出很多有趣的东西，比如记事本之类的。

是的，非常期待
