### ISSUE TITLE
macbook air m1 安装 Noi_macos_0.2.0-arm64.dmg 提示已损坏

### ISSUE THREAD

**Issue by zaleGZL** [lencx/Noi#5]
<img width="260" alt="image" src="https://github.com/lencx/Noi/assets/20339327/93f30f67-b1fc-44bf-86b1-cc1edc2750e8">

**Comment by lencx** [comment]
在终端（terminal）里执行这个命令（我没有 Apple 开发者账号来构建应用，会被系统安全拦截）：

```bash
xattr -cr /Applications/Noi.app
```

**Comment by 3DRX** [comment]
或在系统偏好设置 > 安全性与隐私 > 通用 点击“仍要打开”

**Comment by zaleGZL** [comment]
> 或在系统偏好设置 > 安全性与隐私 > 通用 点击“仍要打开”

这种提示已损坏看起来是不会出现这个的。

**Comment by zhangyongcun** [comment]
测试这个命令可以，`xattr -c /Applications/Noi.app`
