### ISSUE TITLE
Gemini不能与ChatGPT同时使用问题输入

### ISSUE THREAD

**Issue by Houmingnan** [lencx/Noi#50]
Gemini不能与ChatGPT同时使用问题输入

**Comment by Houmingnan** [comment]
感谢。插件更新后gemini更换为bard。但是多个ai同时发送信息的入口没有了。请指教该如何操作！
![image](https://github.com/lencx/Noi/assets/132748961/62904bde-a7de-47ef-9d33-7ff501b77441)

**Comment by lencx** [comment]
不是更换为 Bard，需要更新为 Gemini，侧栏左下角的同步按钮也点一下。

**Comment by Houmingnan** [comment]
抱歉，我说错了。确实是由bard更新为geminni，按照操作，侧栏左下角的同步也做了操作，还是没有多窗口同时发送信息的入口。

**Comment by Houmingnan** [comment]
感谢！问题已经解决！！
