### ISSUE TITLE
wind7(64):无法定位程序输入点DiscardVirtualMemory于动态链接库Kernel32.dll上

### ISSUE THREAD

**Issue by bill-2021** [lencx/Noi#51]
**system**:windows 7(64)
情况:无法安装，提示“无法定位程序输入点DiscardVirtualMemory于动态链接库Kernel32.dll上”

**system**:windows 7(64)
Situation: Unable to install, message "Unable to locate program input point DiscardVirtualMemory on dynamic link library Kernel32.dll"

**Comment by lencx** [comment]
win7 暂时无法定位，我没有测试机

**Comment by bill-2021** [comment]
> 很抱歉，目前软件依赖的框架版本已经放弃了对 win7 的支持。只能升级系统了。 当前是 28 版本，23 就已经放弃支持了。 https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support

现在的Ｎoi是与旧的Chatgpt客户端一样，不用APi，只需要用帐户和密码登陆的吗？如果Noi是要Api的，那有没有只用帐户和密码登陆的同类推荐？谢谢

**Comment by lencx** [comment]
Noi 是与 ChatGPT 客户端一样，都是走网页
