### ISSUE TITLE
更新同步书签后左侧书签无变化

### ISSUE THREAD

**Issue by betterMax** [lencx/Noi#52]
感谢lencx的另一个大作！反馈两个小问题

![image](https://github.com/lencx/Noi/assets/23434996/8ddbb773-7917-46bb-a41c-88119aed7aa3)
已经按照介绍更新了书签地址，并点击了红框里两处同步按钮，但是左侧书签栏没有变化。另外同步点击后最好可以有一些反馈，不然也不知道有没有点击成功。

另外取消了窗口置顶之后，设置窗口似乎依然是被置顶的。

**Comment by lencx** [comment]
看这里，你的链接错了：https://github.com/lencx/Noi/tree/main/configs#sync-url

**Comment by betterMax** [comment]
> 看这里，你的链接错了：https://github.com/lencx/Noi/tree/main/configs#sync-url

非常感谢及时回复，不好意思这会儿才回。我是根据[微信文章](https://mp.weixin.qq.com/s/M6gO6MdK5obCvs2LIBZA3w)里提到的主流 AI 及国内 AI那个书签来的。上面您提供的这个链接里请问包含国内的AI嘛？
