### ISSUE TITLE
Copilot在Noi内不能使用

### ISSUE THREAD

**Issue by Houmingnan** [lencx/Noi#53]
大佬，我在使用Noi时，Copilot时可以登录并可以查看过往历史记录，但不能进行新对话，一直提示“尝试重新连接”。同样的网络在Chrome可以顺利访问Copilot。请大佬指教该如何解决。

**Comment by lencx** [comment]
Copilot 的检测机制我也没搞明白，有时成功，有时失败，可以换节点试试

**Comment by Houmingnan** [comment]
大佬辛苦了，更换了节点也没管用，我再多试试！

**Comment by Donnie-Liang** [comment]
感觉就是节点问题，我用零度云就可以上，换StrongVPN就上不了。

**Comment by Aiuan** [comment]
![image](https://github.com/lencx/Noi/assets/47709353/86da6651-efed-447e-99ca-4a94bace764a)
我也遇见了相同的问题
