### ISSUE TITLE
Prompt  标签添加

### ISSUE THREAD

**Issue by raylyli** [lencx/Noi#55]
windows版本，这个标签是不是无法添加？
![band](https://github.com/lencx/Noi/assets/85328477/e82169fa-946f-442d-b245-d6d4534595c9)

**Comment by joesima** [comment]
你好，看到你的照片中标签选项并没有红色星标，并不是必须的选项，应该可以不填，可以试一试

**Comment by lencx** [comment]
默认没有标签，需要自己创建，然后选择
