### ISSUE TITLE
'Stick on top' 选项开启后，noi主界面会在noisetting界面的上方，若不缩小则无法再进行配置

### ISSUE THREAD

**Issue by TianzeWang** [lencx/Noi#59]

**Comment by lencx** [comment]
可以先尝试将主界面取消置顶，点击侧栏也是可以直接设置置顶的。

<img width="207" alt="noi sidebar" src="https://github.com/lencx/Noi/assets/16164244/88b06aca-9d66-4b86-a416-596ff76e0829">
