### ISSUE TITLE
一次打开多个聊天ai时，gemini不能录入内容

### ISSUE THREAD

**Issue by lelelaileabc** [lencx/Noi#63]
![微信截图_20240224150728](https://github.com/lencx/Noi/assets/8361688/835e730b-e8b3-4b4f-bd30-834e010e49db)

**Comment by lencx** [comment]
Gemini 从 Bard 更新过来的，之前的插件失效了，你可以在 readme 中国地区的两篇文章中看一下如何更新插件。
