### ISSUE TITLE
打开新聊天的快捷键能改吗？

### ISSUE THREAD

**Issue by zcsunt** [lencx/Noi#66]
跟其他应用的快捷键冲突了，目前没有办法改，而且也没有实现同样功能的按钮可以点击，希望设置里提供改快捷键的选项或提供按钮。

**Comment by lencx** [comment]
打开新聊天没有快捷键啊，你说的是哪里？麻烦提供一下截图

**Comment by zcsunt** [comment]
<img width="142" alt="image" src="https://github.com/lencx/Noi/assets/2011989/62819644-1529-454f-97d8-e4221a9b43a3">

**Comment by lencx** [comment]
这是是刷新页面（当页面刷新后，所有对话会新开，类似于新建），而且只在 Noi 中生效，为啥会冲突？

**Comment by lencx** [comment]
那只能说你的全局快捷键设置不合理，所有浏览器默认的刷新快捷键都是 `Cmd + R`。
