### ISSUE TITLE
请提供清理缓存的功能，否则账号出问题后只能删除重装

### ISSUE THREAD

**Issue by WranglerFan** [lencx/Noi#67]
非常感谢你的付出。软件非常好。现在有个问题：
之前一直用的plus贴号被封了，无法登录。在浏览器中清理缓存后才能登录其他账号。但Noi输入其他账号登录后，还是提示被封账号的出错信息。只有删除APP后，重装才能正常登录其他账号。我使用MacOS。

**Comment by lencx** [comment]
> 但Noi输入其他账号登录后，还是提示被封账号的出错信息。只有删除APP后，重装才能正常登录其他账号。我使用MacOS。

可以尝试清除缓存，点击这个按钮即可。

<img width="370" alt="noi clear cache" src="https://github.com/lencx/Noi/assets/16164244/9e392d18-d20b-4d73-8172-ffd1db188b1c">
