### ISSUE TITLE
Send message doesn't work for Bard

### ISSUE THREAD

**Issue by 3DRX** [lencx/Noi#7]
version: v0.2.0 MacOS 12.7.2 intel

https://github.com/lencx/Noi/assets/67278980/66911ea9-2a21-405b-b724-fe895ceca3a4

**Comment by lencx** [comment]
这里写了两篇文章介绍 Noi，可以看一下，第二篇着重介绍了插件相关的内容：
- https://mp.weixin.qq.com/s/dAN7LOw7mH609HdAyEvXfg
- https://mp.weixin.qq.com/s/M6gO6MdK5obCvs2LIBZA3w
