### ISSUE TITLE
mac 全屏使用时 vscode 无法撑满屏幕

### ISSUE THREAD

**Issue by littlemoji** [lencx/Noi#70]
![image](https://github.com/lencx/Noi/assets/55924059/40df1193-378e-4beb-8ef4-167cbfb6ba28)

**Comment by lencx** [comment]
是否连接大屏了，目前已知在多屏上会导致一些计算错误。

**Comment by lencx** [comment]
我没有多屏幕进行测试，你可以尝试下载 v0.4.0 查看问题是否被解决。
