### ISSUE TITLE
文件管理

### ISSUE THREAD

**Issue by YQisme** [lencx/Noi#74]
能否可以直接在文件夹下创建链接，而不用创建链接后再拖入到文件夹中

**Comment by lencx** [comment]
暂不支持，更高效的方式是直接打开侧栏的配置文件，自己去修改数据，在 Help 菜单中可以找到 `
Noi UserData -> Noi Config -> Noi.conf.json`

注意：不要修改错了 json 数据格式，否则程序会加载错误。

**Comment by lencx** [comment]
对了，补充一点，不建议修改 `noi.mode.json`，这个在同步时会被覆盖，在同级目录中有个 `user.mode.json`，可以修改它。
