### ISSUE TITLE
对于代理，建议添加一个开关来启用和禁用它

### ISSUE THREAD

**Issue by abgox** [lencx/Noi#76]
- 当我不想使用代理时，在当前的版本，我只能通过清空规则
- 但是我下次需要使用代理时，又得重新添加
- 所以建议添加一个开关，不用清空规则，只需要启用或禁用它

**Comment by abgox** [comment]
我暂时没有遇到过，也有可能我有时开了全局代理的原因

**Comment by lencx** [comment]
好的，如果遇到了，忽略这个问题就可以了，我下个版本会修复。

**Comment by ws19** [comment]
> 安排，下个版本支持。目前 proxy 设置应该是有 bug 的，它有几率是在网页加载之后才设置，导致 proxy 不生效，你没遇到过吗？

我使用目标里的 --proxy-server="127.0.0.1:10801" 遇到 打开软件白屏的问题，请问知道咋回事吗，目前用的win10 ，v2rayN开的socket5

**Comment by lencx** [comment]
目前代理设置存在 bug，即使设置正确，也有很大几率不生效。

**Comment by ws19** [comment]
> 目前代理设置存在 bug，即使设置正确，也有很大几率不生效。

之前刚用的时候没有碰到这个情况，现在就没好过😂

**Comment by lencx** [comment]
请下载 v0.4.0 版本，此功能已实现。

**Comment by lencx** [comment]
你的 Noi 是如何配置的？

**Comment by ZhenhongDu** [comment]
@lencx 您好，作者大大，

我想请问一下多个绕过规则如何设置，对于国内的ai产品，我使用下面的规则
`localhost;<local>; *.tiangong.cn; *.aliyun.com; so.chat.360.cn`
对阿里云的通义有效，但无法对[www.tiangong.cn](www.tiangong.cn)起作用
![image](https://github.com/lencx/Noi/assets/61380549/c9edb78c-4683-46ff-84ef-591d83c9e3fc)

**Comment by ZhenhongDu** [comment]
> @lencx 您好，作者大大，
> 
> 我想请问一下多个绕过规则如何设置，对于国内的ai产品，我使用下面的规则 `localhost;<local>; *.tiangong.cn; *.aliyun.com; so.chat.360.cn` 对阿里云的通义有效，但无法对[www.tiangong.cn](www.tiangong.cn)起作用 ![image](https://private-user-images.githubusercontent.com/61380549/334779611-c9edb78c-4683-46ff-84ef-591d83c9e3fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODIzMzksIm5iZiI6MTcxNjk4MjAzOSwicGF0aCI6Ii82MTM4MDU0OS8zMzQ3Nzk2MTEtYzllZGI3OGMtNDY4My00NmZmLTg0ZWYtNTkxZDgzYzllM2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5Njg3NjRlMTgyOTJjY2U1ZTE3MzNjZTNiMDdlNzNjYTJjNTU1MGMwZDM0ZWI0NWRhY2Q5ZjNkNjFmNDJjMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cvuvTw9JNyUPS7SGLqoX-6V1DDvZrKm7AvFgCNVMAVM)

版本是：Noi v0.4.0
