### ISSUE TITLE
Noi.exe 无法找到入口 Windows 7 - dynamic link library Kernel32.dll Error | Entry Point Not Found

### ISSUE THREAD

**Issue by qingquan214** [lencx/Noi#77]
win7 X64 安装时存在错误
Windows 7 - How to fixed dynamic link library Kernel32.dll Error | Entry Point Not Found ?
![20240302103020](https://github.com/lencx/Noi/assets/46894795/92df2745-032a-454e-8d3f-cd74e611c54f)

**Comment by lencx** [comment]
win7 不支持。
