### ISSUE TITLE
[feature request] use SHIFT + ENTER to send prompt

### ISSUE THREAD

**Issue by spiritually-soup** [lencx/Noi#78]
under `prompt send` settings, current options are

- `cmd` + `enter`
- `ctrl` + `enter`
- `enter`

it would be great if you can add an option to use  `shift` + `enter` 
some users like me are more used to that, and it is common in other apps / websites :)

thank you!

**Comment by lencx** [comment]
Thank you for the suggestion, it will be supported in the next version.

**Comment by lencx** [comment]
Please download v0.4.0
