### ISSUE TITLE
GitHub 更新fork的仓库会失败，切换到正常浏览器就成功了。

### ISSUE THREAD

**Issue by zsychn** [lencx/Noi#8]

**Comment by zsychn** [comment]
<img width="353" alt="image" src="https://github.com/lencx/Noi/assets/23525693/e89d81c0-638a-4e3d-9d6f-291103decd45">
就这里，点update没有反应，但我切换到其他浏览器，完成了更新。

**Comment by lencx** [comment]
请下载 v0.2.1 尝试一下

**Comment by zsychn** [comment]
经过测试，已OK。辛苦。
