### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by jemima03** [lencx/Noi#83]
公司电脑win10上更改了“ctrl+shift+N”默认开启面板快捷键，就出现了这个问题，并且重装也没能解决，
回家拿自己的win11测试了也是同样的问题。😭

**Comment by lencx** [comment]
可以截图看一下吗，可能是快捷键冲突了。可以先通过修改配置文件解决。

打开 `C:\Users\Username\AppData\Roaming\Noi\noi_configs\noi.conf.json` 文件，修改 `global_shortcut` 为空字段，重新启动。

**Comment by jemima03** [comment]
第一次用github反馈问题，所以还不太会。按照你说的修改后还是不行
![PixPin_2024-03-09_15-31-50](https://github.com/lencx/Noi/assets/91102670/68527884-fa35-4081-8e27-1ab3951426fc)

**Comment by lencx** [comment]
是因为你重复打开 Noi 了，你先确保它完全退出。之前并未做快捷键边界处理，重复注册会导致程序崩溃。

**Comment by jemima03** [comment]
非常感谢！确实是这个问题！因为我点一次是没有任何反应的，会下意识的再点多一次，然后就出现这种弹窗了。我按照你提供的那种方法，改成空字段，退出后台，就解决了。现在又乖乖改回默认键了，只有默认键没问题😂

**Comment by lencx** [comment]
默认快捷键是可以修改为自定义的，可能是你之前定义的快捷键冲突或者之前已经开启了一个 Noi，你可以再试试。

**Comment by lencx** [comment]
请下载 v0.4.0 版本
