### ISSUE TITLE
localhost本地访问

### ISSUE THREAD

**Issue by YQisme** [lencx/Noi#89]
有意向把noi当作一个门户工具，希望增加此功能
![image](https://github.com/lencx/Noi/assets/80308783/d55ac12a-d7a3-4199-b514-5dc09c6feabb)

**Comment by lencx** [comment]
下个版本放开此校验。目前可以通过手动编辑文件来解决。
`C:\Users\Username\AppData\Roaming\Noi\noi_configs\user.mode.json`

**Comment by YQisme** [comment]
> 下个版本放开此校验。目前可以通过手动编辑文件来解决： `C:\Users\Username\AppData\Roaming\Noi\noi_configs\user.mode.json`
> 
> 编辑后，重启一下应用。

ok
