### ISSUE TITLE
win10打开有绿色动画效果显示, 然后一片空白

### ISSUE THREAD

**Issue by jun-jing** [lencx/Noi#9]
**点击安装exe后, 显示绿色动效**
![QQ截图20240124154942](https://github.com/lencx/Noi/assets/18417195/ad14f50e-349e-446c-a9ed-7b34435fd284)

**接着进入白屏状态**
![QQ截图20240124154949](https://github.com/lencx/Noi/assets/18417195/5c818d24-5734-46c8-94f8-0f99627afbe3)

**电脑配置**
![QQ截图20240124155025](https://github.com/lencx/Noi/assets/18417195/45d818cf-4cec-436d-bb59-e9b44a670b20)

**Comment by gaojian66** [comment]
same   question

**Comment by lencx** [comment]
请下载 v0.2.1
