### ISSUE TITLE
如何选择默认浏览器打开外链？

### ISSUE THREAD

**Issue by Mickychen00** [lencx/Noi#90]
在设置中并未找到。

**Comment by lencx** [comment]
下个版本会支持网页右键菜单打开默认浏览器

**Comment by Mickychen00** [comment]
好的，谢谢。建议在软件设置层级就可以选择使用默认浏览器打开，原因在于默认浏览器对PAC模式支持更好，避免所打开的网页无法访问。

**Comment by lencx** [comment]
点击这里就是浏览器打开啊，这个之前就支持

![image](https://github.com/lencx/Noi/assets/16164244/5e6ecab1-0c92-4c5f-9be5-d8ee39b1b6f7)

**Comment by Mickychen00** [comment]
抱歉 我没说清楚 我的意思是当AI给出某些回答时，会提供许多外链（比如Perplexity），当我点击外链时，会自动使用Noi内置浏览器，我想得是可以自己选择使用内置还是默认浏览器。

**Comment by lencx** [comment]
请下载 v0.4.0 版本，此功能已实现。可以通过右键菜单在默认浏览器打开。
