### ISSUE TITLE
Error_Report_JavascriptError

### ISSUE THREAD

**Issue by RyanHensson10729** [lencx/Noi#92]
![noi error](https://github.com/lencx/Noi/assets/47966024/5d1744db-68e7-4a83-a6ab-1620ba395139)
The error occured when I was using Ctrl+Shift+N in Rstudio to create a new file in Windows 10 22H2 19045.4170. The Noi program cracked withour pop-up windows or hints. When I realized and tried to restart, it failed with the pop-up window showing the messages as the attached file reads. More information could be provided if needed. Thanks.

**Comment by lencx** [comment]
This is because there is a conflict with global shortcuts. You can try completely exiting the application and reopening it.

**Comment by RyanHessson** [comment]
> This is because there is a conflict with global shortcuts. You can try completely exiting the application and reopening it.

I have tried several times but the relaunch method seems not working well. The same error and window is displayed. What else would you think I may try? Thanks.

**Comment by RyanHessson** [comment]
> This is because there is a conflict with global shortcuts. You can try completely exiting the application and reopening it.

I used task manager to terminate all sessions, as has been implied, and that worked. Thank you. However, is there a way to completely avoid this problem? Do I need to configure pertinently or a update patch could be expected? Thanks!

**Comment by lencx** [comment]
This is because the shortcut key is already occupied by an application that is running, so registering the shortcut key again will fail. I will optimize the error message in the next version.

**Comment by lencx** [comment]
Please download v0.4.0!
However, it does not resolve shortcut key conflicts; it merely optimizes the error messages.
